ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0

USER_LIB_PATH = ./libraries
ARDUINO_LIBS += SPI MFRC522
BOARD_TAG = mega
BOARD_SUB = atmega2560

# Décommenter si problème de path qui se génère mal

#ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/avr/variants
#BOARDS_TXT = /usr/share/arduino/hardware/arduino/avr/boards.txt
#ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
#BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/avr/bootloaders

include /usr/share/arduino/Arduino.mk
