ARDUINO_VARIANT = lolin32
SERIAL_PORT = /dev/ttyUSB0
# uncomment and set the right serail baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
# uncomment this to use the 1M SPIFFS mapping
#SPIFFS_SIZE = 1
#ESP8266_VERSION=git
ARDUINO_LIBS=WiFiClientSecure ArduinoJson
ARDUINO_ARCH=esp32

include ../arduino/Esp8266-Arduino-Makefile/espXArduino.mk


